# application.yml

server:
  port: 8080
  servlet:
    context-path: /crypto-monitor

spring:
  application:
    name: crypto-monitor

  # Configuração do banco de dados PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_monitor
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:crypto_user}
    password: ${DB_PASSWORD:qwe123}

  # Configuração JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: none  # ALTERADO: era 'update', agora 'none' para deixar o Flyway gerenciar
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: false  # ALTERADO: era true, agora false

  database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Flyway migration config
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/crypto_monitor
    user: ${DB_USERNAME:crypto_user}
    password: ${DB_PASSWORD:qwe123}
    baseline-on-migrate: true
    validate-on-migrate: true  # ADICIONADO: valida as migrações
    out-of-order: false        # ADICIONADO: garante ordem das migrações

  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET:crypto-monitor-super-secret-key-that-should-be-changed-in-production-environment}
    expiration: ${JWT_EXPIRATION:86400000} # 24 horas em milissegundos

  # Configuração de Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:testeprojeto0001@gmail.com}
    password: ${MAIL_PASSWORD:cuuiungfqytluwrr}  # CORRIGIDO: removidos espaços
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# Configurações da aplicação
crypto:
  coins: bitcoin,ethereum,cardano,polkadot,chainlink,solana,avalanche-2,polygon,litecoin,bitcoin-cash

# Configurações de alertas
alert:
  buy:
    threshold: -1.0  # ALTERADO: de -5.0 para -1.0 para testar alertas mais facilmente
  sell:
    threshold: 1.0   # ALTERADO: de 10.0 para 1.0 para testar alertas mais facilmente

# Configurações de notificação
notification:
  email:
    enabled: true
    from: ${MAIL_USERNAME:testeprojeto0001@gmail.com}
    to: ${NOTIFICATION_EMAIL:testeprojeto0001@gmail.com}

  telegram:
    enabled: ${TELEGRAM_ENABLED:false}
    bot-token: ${TELEGRAM_BOT_TOKEN:}
    chat-id: ${TELEGRAM_CHAT_ID:}

# Configuração da API CoinGecko
coingecko:
  api:
    url: https://api.coingecko.com/api/v3

# Configuração de logs
logging:
  level:
    com.crypto: INFO
    org.springframework.web: DEBUG
    org.springframework.mail: DEBUG
    org.flywaydb: DEBUG  # ADICIONADO: logs do Flyway para debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/crypto-monitor.log

# Configuração do Actuator (monitoramento)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false  # ADICIONADO: desabilita health check de email
  info:
    env:
      enabled: true

# Informações da aplicação
info:
  app:
    name: Crypto Monitor
    description: Sistema de Monitoramento de Criptomoedas
    version: 1.0.0
  java:
    version: "17.0.16"
  build:
    timestamp: ${TIMESTAMP}